<?php
$i = 0;
$category_icon = array(
    "អចលនទ្រព្យ",
    "សម្រស់",
    "សុខភាព",
    "អាហារ",
    "យាន្តយន្ត",
    "សេវាកម្ម",
    "Forex"
);
$icon = array(
    "'bx bxs-circle''",
    "'bx bxs-circle''",
    "'bx bxs-circle'",
    "'bx bxs-circle'",
    "'bx bxs-circle'",
    "'bx bxs-circle'",
    "'bx bxs-circle'",
    "'bx bxs-circle'",
    "'bx bxs-circle'",
    "'bx bxs-circle'",
    "'bx bxs-circle'",
    "'bx bxs-circle'",
    "'bx bxs-circle'",
    "'bx bxs-circle'",
    "'bx bxs-circle'",
    "'bx bxs-circle'",
    "'bx bxs-circle'",
    "'bx bxs-circle'",
    "'bx bxs-circle'",
    "'bx bxs-circle'",
    "'bx bxs-circle'",
    "'bx bxs-circle'",
    "'bx bxs-circle'",
    "'bx bxs-circle'",
    "'bx bxs-circle'",
    "'bx bxs-circle'",
    "'bx bxs-circle'",
    "'bx bxs-circle'",
    "'bx bxs-circle'",
    "'bx bxs-circle'",
    "'bx bxs-circle'",
    "'bx bxs-circle'",
    "'bx bxs-circle'",
    "'bx bxs-circle'",
    "'bx bxs-circle'",
    "'bx bxs-circle'",
    "'bx bxs-circle'",
    "'bx bxs-circle'",
    "'bx bxs-circle'",
    "'bx bxs-circle'"
);
